name       : catbox
version    : 1.7.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/c/catbox/catbox-1.7.0.tar.gz : f0f066048679a9f5a00b9ccd83c06fb0b98d5d5f27dab1ba0c6ef325e71db109
license    : GPL-2.0-or-later
component  : system.devel
summary    : Fast sandbox implementation for Python
description: |
    Catbox is a sandbox for Python which provides a tightly-controlled set of resources for guest programs to run in. It is used for security and testing purposes, largely during the building of packages. Catbox was originally written for Pardus Linux.
builddeps  :
    - python-setuptools
build      : |
    %python_setup --enable-pcre
install    : |
    %python_install
